# action.yml
name: 'Simpl Sharp'
description: 'Greet someone and record the time'
inputs:
  project: 
    description: 'Project file targeting the simplsharp SDK'
    required: true
    default: './**.csproj'
  targets: 
    description: 'Target dotnet framework'
    required: false
    default: 'net472'
  configuration: 
    description: 'Target configuration'
    required: false
    default: 'Release'
    
outputs:
  cpz_file:
    description: 'The location of the new CPZ file on the runner'
  clz_file:
    description: 'The location of the new CLZ file on the runner'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.targets }}
    - ${{ inputs.configuration }}